import 'dart:core';

class CityModel {
  String? name;
  String? localNames;
  double? lat;
  double? lon;
  String? country;
  String? state;

  CityModel({this.name, this.localNames, this.lat, this.lon, this.country, this.state});

  CityModel.fromJson(Map<String, dynamic> json) {
    name = json['name'];
   // localNames = json['local_names'] != null ? new LocalNames.fromJson(json['local_names']) : null;
    lat = json['lat'];
    lon = json['lon'];
    country = json['country'];
    state = json['state'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    // if (this.localNames != null) {
    //   data['local_names'] = this.localNames!.toJson();
    // }
    data['lat'] = this.lat;
    data['lon'] = this.lon;
    data['country'] = this.country;
    data['state'] = this.state;
    return data;
  }
}

// class LocalNames {
//   var? cy;
//   String? pa;
//   String? om;
//   String? el;
//   String? ml;
//   String? na;
//   String? gl;
//   String? av;
//   String? hy;
//   String? fo;
//   String? br;
//   String? wa;
//   String? mt;
//   String? km;
//   String? my;
//   String? nn;
//   String? es;
//   String? lv;
//   String? de;
//   String? kn;
//   String? jv;
//   String? featureName;
//   String? si;
//   String? ascii;
//   String? ba;
//   String? zu;
//   String? to;
//   String? ny;
//   String? ha;
//   String? qu;
//   String? sk;
//   String? zh;
//   String? li;
//   String? ig;
//   String? se;
//   String? mn;
//   String? te;
//   String? az;
//   String? ff;
//   String? fj;
//   String? pl;
//   String? bs;
//   String? sl;
//   String? af;
//   String? fy;
//   String? am;
//   String? yi;
//   String? cu;
//   String? pt;
//   String? sd;
//   String? vi;
//   String? st;
//   String? bn;
//   String? ps;
//   String? nl;
//   String? io;
//   String? ee;
//   String? gd;
//   String? cv;
//   String? vo;
//   String? kl;
//   String? he;
//   String? ne;
//   String? no;
//   String? ky;
//   String? mk;
//   String? nv;
//   String? ru;
//   String? bo;
//   String? hu;
//   String? gu;
//   String? tg;
//   String? eo;
//   String? lo;
//   String? tk;
//   String? ka;
//   String? bi;
//   String? ga;
//   String? id;
//   String? kk;
//   String? da;
//   String? sh;
//   String? ca;
//   String? fa;
//   String? fr;
//   String? bh;
//   String? lb;
//   String? bg;
//   String? so;
//   String? bm;
//   String? ia;
//   String? an;
//   String? be;
//   String? kw;
//   String? sw;
//   String? ta;
//   String? wo;
//   String? ko;
//   String? mi;
//   String? ur;
//   String? is;
//   String? sr;
//   String? yo;
//   String? os;
//   String? ja;
//   String? sm;
//   String? mr;
//   String? uz;
//   String? th;
//   String? ro;
//   String? ab;
//   String? rm;
//   String? co;
//   String? mg;
//   String? su;
//   String? sc;
//   String? oc;
//   String? ms;
//   String? tr;
//   String? fi;
//   String? tl;
//   String? tw;
//   String? or;
//   String? et;
//   String? ie;
//   String? sa;
//   String? ug;
//   String? ar;
//   String? ht;
//   String? ce;
//   String? eu;
//   String? lt;
//   String? ku;
//   String? it;
//   String? hi;
//   String? en;
//   String? hr;
//   String? gn;
//   String? sq;
//   String? ay;
//   String? gv;
//   String? uk;
//   String? sv;
//   String? sn;
//   String? ln;
//   String? cs;
//   String? kv;
//   String? tt;
//
//  // LocalNames({this.cy, this.pa, this.om, this.el, this.ml, this.na, this.gl, this.av, this.hy, this.fo, this.br, this.wa, this.mt, this.km, this.my, this.nn, this.es, this.lv, this.de, this.kn, this.jv, this.featureName, this.si, this.ascii, this.ba, this.zu, this.to, this.ny, this.ha, this.qu, this.sk, this.zh, this.li, this.ig, this.se, this.mn, this.te, this.az, this.ff, this.fj, this.pl, this.bs, this.sl, this.af, this.fy, this.am, this.yi, this.cu, this.pt, this.sd, this.vi, this.st, this.bn, this.ps, this.nl, this.io, this.ee, this.gd, this.cv, this.vo, this.kl, this.he, this.ne, this.no, this.ky, this.mk, this.nv, this.ru, this.bo, this.hu, this.gu, this.tg, this.eo, this.lo, this.tk, this.ka, this.bi, this.ga, this.id, this.kk, this.da, this.sh, this.ca, this.fa, this.fr, this.bh, this.lb, this.bg, this.so, this.bm, this.ia, this.an, this.be, this.kw, this.sw, this.ta, this.wo, this.ko, this.mi, this.ur, this.is, this.sr, this.yo, this.os, this.ja, this.sm, this.mr, this.uz, this.th, this.ro, this.ab, this.rm, this.co, this.mg, this.su, this.sc, this.oc, this.ms, this.tr, this.fi, this.tl, this.tw, this.or, this.et, this.ie, this.sa, this.ug, this.ar, this.ht, this.ce, this.eu, this.lt, this.ku, this.it, this.hi, this.en, this.hr, this.gn, this.sq, this.ay, this.gv, this.uk, this.sv, this.sn, this.ln, this.cs, this.kv, this.tt});
//
// LocalNames.fromJson(Map<String, dynamic> json) {
// cy = json['cy'];
// pa = json['pa'];
// om = json['om'];
// el = json['el'];
// ml = json['ml'];
// na = json['na'];
// gl = json['gl'];
// av = json['av'];
// hy = json['hy'];
// fo = json['fo'];
// br = json['br'];
// wa = json['wa'];
// mt = json['mt'];
// km = json['km'];
// my = json['my'];
// nn = json['nn'];
// es = json['es'];
// lv = json['lv'];
// de = json['de'];
// kn = json['kn'];
// jv = json['jv'];
// featureName = json['feature_name'];
// si = json['si'];
// ascii = json['ascii'];
// ba = json['ba'];
// zu = json['zu'];
// to = json['to'];
// ny = json['ny'];
// ha = json['ha'];
// qu = json['qu'];
// sk = json['sk'];
// zh = json['zh'];
// li = json['li'];
// ig = json['ig'];
// se = json['se'];
// mn = json['mn'];
// te = json['te'];
// az = json['az'];
// ff = json['ff'];
// fj = json['fj'];
// pl = json['pl'];
// bs = json['bs'];
// sl = json['sl'];
// af = json['af'];
// fy = json['fy'];
// am = json['am'];
// yi = json['yi'];
// cu = json['cu'];
// pt = json['pt'];
// sd = json['sd'];
// vi = json['vi'];
// st = json['st'];
// bn = json['bn'];
// ps = json['ps'];
// nl = json['nl'];
// io = json['io'];
// ee = json['ee'];
// gd = json['gd'];
// cv = json['cv'];
// vo = json['vo'];
// kl = json['kl'];
// he = json['he'];
// ne = json['ne'];
// no = json['no'];
// ky = json['ky'];
// mk = json['mk'];
// nv = json['nv'];
// ru = json['ru'];
// bo = json['bo'];
// hu = json['hu'];
// gu = json['gu'];
// tg = json['tg'];
// eo = json['eo'];
// lo = json['lo'];
// tk = json['tk'];
// ka = json['ka'];
// bi = json['bi'];
// ga = json['ga'];
// id = json['id'];
// kk = json['kk'];
// da = json['da'];
// sh = json['sh'];
// ca = json['ca'];
// fa = json['fa'];
// fr = json['fr'];
// bh = json['bh'];
// lb = json['lb'];
// bg = json['bg'];
// so = json['so'];
// bm = json['bm'];
// ia = json['ia'];
// an = json['an'];
// be = json['be'];
// kw = json['kw'];
// sw = json['sw'];
// ta = json['ta'];
// wo = json['wo'];
// ko = json['ko'];
// mi = json['mi'];
// ur = json['ur'];
// is = json['is'];
// sr = json['sr'];
// yo = json['yo'];
// os = json['os'];
// ja = json['ja'];
// sm = json['sm'];
// mr = json['mr'];
// uz = json['uz'];
// th = json['th'];
// ro = json['ro'];
// ab = json['ab'];
// rm = json['rm'];
// co = json['co'];
// mg = json['mg'];
// su = json['su'];
// sc = json['sc'];
// oc = json['oc'];
// ms = json['ms'];
// tr = json['tr'];
// fi = json['fi'];
// tl = json['tl'];
// tw = json['tw'];
// or = json['or'];
// et = json['et'];
// ie = json['ie'];
// sa = json['sa'];
// ug = json['ug'];
// ar = json['ar'];
// ht = json['ht'];
// ce = json['ce'];
// eu = json['eu'];
// lt = json['lt'];
// ku = json['ku'];
// it = json['it'];
// hi = json['hi'];
// en = json['en'];
// hr = json['hr'];
// gn = json['gn'];
// sq = json['sq'];
// ay = json['ay'];
// gv = json['gv'];
// uk = json['uk'];
// sv = json['sv'];
// sn = json['sn'];
// ln = json['ln'];
// cs = json['cs'];
// kv = json['kv'];
// tt = json['tt'];
// }
//
// Map<String, dynamic> toJson() {
// final Map<String, dynamic> data = new Map<String, dynamic>();
// data['cy'] = this.cy;
// data['pa'] = this.pa;
// data['om'] = this.om;
// data['el'] = this.el;
// data['ml'] = this.ml;
// data['na'] = this.na;
// data['gl'] = this.gl;
// data['av'] = this.av;
// data['hy'] = this.hy;
// data['fo'] = this.fo;
// data['br'] = this.br;
// data['wa'] = this.wa;
// data['mt'] = this.mt;
// data['km'] = this.km;
// data['my'] = this.my;
// data['nn'] = this.nn;
// data['es'] = this.es;
// data['lv'] = this.lv;
// data['de'] = this.de;
// data['kn'] = this.kn;
// data['jv'] = this.jv;
// data['feature_name'] = this.featureName;
// data['si'] = this.si;
// data['ascii'] = this.ascii;
// data['ba'] = this.ba;
// data['zu'] = this.zu;
// data['to'] = this.to;
// data['ny'] = this.ny;
// data['ha'] = this.ha;
// data['qu'] = this.qu;
// data['sk'] = this.sk;
// data['zh'] = this.zh;
// data['li'] = this.li;
// data['ig'] = this.ig;
// data['se'] = this.se;
// data['mn'] = this.mn;
// data['te'] = this.te;
// data['az'] = this.az;
// data['ff'] = this.ff;
// data['fj'] = this.fj;
// data['pl'] = this.pl;
// data['bs'] = this.bs;
// data['sl'] = this.sl;
// data['af'] = this.af;
// data['fy'] = this.fy;
// data['am'] = this.am;
// data['yi'] = this.yi;
// data['cu'] = this.cu;
// data['pt'] = this.pt;
// data['sd'] = this.sd;
// data['vi'] = this.vi;
// data['st'] = this.st;
// data['bn'] = this.bn;
// data['ps'] = this.ps;
// data['nl'] = this.nl;
// data['io'] = this.io;
// data['ee'] = this.ee;
// data['gd'] = this.gd;
// data['cv'] = this.cv;
// data['vo'] = this.vo;
// data['kl'] = this.kl;
// data['he'] = this.he;
// data['ne'] = this.ne;
// data['no'] = this.no;
// data['ky'] = this.ky;
// data['mk'] = this.mk;
// data['nv'] = this.nv;
// data['ru'] = this.ru;
// data['bo'] = this.bo;
// data['hu'] = this.hu;
// data['gu'] = this.gu;
// data['tg'] = this.tg;
// data['eo'] = this.eo;
// data['lo'] = this.lo;
// data['tk'] = this.tk;
// data['ka'] = this.ka;
// data['bi'] = this.bi;
// data['ga'] = this.ga;
// data['id'] = this.id;
// data['kk'] = this.kk;
// data['da'] = this.da;
// data['sh'] = this.sh;
// data['ca'] = this.ca;
// data['fa'] = this.fa;
// data['fr'] = this.fr;
// data['bh'] = this.bh;
// data['lb'] = this.lb;
// data['bg'] = this.bg;
// data['so'] = this.so;
// data['bm'] = this.bm;
// data['ia'] = this.ia;
// data['an'] = this.an;
// data['be'] = this.be;
// data['kw'] = this.kw;
// data['sw'] = this.sw;
// data['ta'] = this.ta;
// data['wo'] = this.wo;
// data['ko'] = this.ko;
// data['mi'] = this.mi;
// data['ur'] = this.ur;
// data['is'] = this.is;
// data['sr'] = this.sr;
// data['yo'] = this.yo;
// data['os'] = this.os;
// data['ja'] = this.ja;
// data['sm'] = this.sm;
// data['mr'] = this.mr;
// data['uz'] = this.uz;
// data['th'] = this.th;
// data['ro'] = this.ro;
// data['ab'] = this.ab;
// data['rm'] = this.rm;
// data['co'] = this.co;
// data['mg'] = this.mg;
// data['su'] = this.su;
// data['sc'] = this.sc;
// data['oc'] = this.oc;
// data['ms'] = this.ms;
// data['tr'] = this.tr;
// data['fi'] = this.fi;
// data['tl'] = this.tl;
// data['tw'] = this.tw;
// data['or'] = this.or;
// data['et'] = this.et;
// data['ie'] = this.ie;
// data['sa'] = this.sa;
// data['ug'] = this.ug;
// data['ar'] = this.ar;
// data['ht'] = this.ht;
// data['ce'] = this.ce;
// data['eu'] = this.eu;
// data['lt'] = this.lt;
// data['ku'] = this.ku;
// data['it'] = this.it;
// data['hi'] = this.hi;
// data['en'] = this.en;
// data['hr'] = this.hr;
// data['gn'] = this.gn;
// data['sq'] = this.sq;
// data['ay'] = this.ay;
// data['gv'] = this.gv;
// data['uk'] = this.uk;
// data['sv'] = this.sv;
// data['sn'] = this.sn;
// data['ln'] = this.ln;
// data['cs'] = this.cs;
// data['kv'] = this.kv;
// data['tt'] = this.tt;
// return data;
// }

